### ISSUE TITLE
$inline.start/end error

### ISSUE THREAD

**Issue by eight04** [eight04/inline-js#7]
```
<!-- $inline.start("./cli.js|docstring|markdown:codeblock") -->
<!-- $inline.end -->
```
```
inline-js started

D:\Dev\webext-tx-fix\node_modules\inline-js\index.js:176
                                throw new Error(`$inline.start and $inline.end m
ust not present at the same line`);
                                ^

Error: $inline.start and $inline.end must not present at the same line
    at inlines (D:\Dev\webext-tx-fix\node_modules\inline-js\index.js:176:11)
    at inlines.next (<anonymous>)
    at inline (D:\Dev\webext-tx-fix\node_modules\inline-js\index.js:283:19)
    at Object.init (D:\Dev\webext-tx-fix\node_modules\inline-js\index.js:469:13)

    at Object.<anonymous> (D:\Dev\webext-tx-fix\node_modules\inline-js\cli.js:18
:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by eight04** [comment]
Documented in the readme.
